### ISSUE TITLE
CW - The Crashing Wave

### ISSUE THREAD

**Issue by marcsoiferman** [ringteki/ringteki#40]
![image](https://user-images.githubusercontent.com/60416666/73600489-422c0680-4516-11ea-98f2-674b96c97642.png)

**Comment by P4thos** [comment]
@marcsoiferman Could this and the one for Know the Terrain (https://github.com/ringteki/ringteki/issues/153) be resolved and the cards actually working in Jigoku by say, March 28th?  Asking for a friend.
