### ISSUE TITLE
Asahina Augur does not always let its controller look at facedown cards in their provinces

### ISSUE THREAD

**Issue by EBaalhuis** [ringteki/ringteki#428]
I bought an Asahina Augur, and was able to look at the facedown card in the province I bought it from. Then I used the action to discard that facedown card, and was not able to look at the new facedown card in the same province.

![image](https://user-images.githubusercontent.com/14149179/81990289-2bca3680-963f-11ea-848a-91e3707d39ab.png)

**Comment by EBaalhuis** [comment]
Same issue also happens when a new facedown dynasty card is put in a province after you buy a character from it (as opposed to discarding with the Augur action).

**Comment by marcsoiferman** [comment]
Seems to be related to the effect being applied AFTER the state is fetched by the UI

**Comment by marcsoiferman** [comment]
Maybe not? Not sure.

**Comment by marcsoiferman** [comment]
Actually, looks like the effect doesn't get applied to cards until the next game state update after the card enters the province.
