### ISSUE TITLE
Bug - Presumed to be Silent Ones w/Honor Transfer

### ISSUE THREAD

**Issue by marcsoiferman** [ringteki/ringteki#459]
Turn: 2 - Draw Phase
akodobill1 has chosen a bid.
Dare has chosen a bid.
akodobill1 reveals a bid of 1
Dare reveals a bid of 3
Dare gives akodobill1 2 honor
akodobill1 draws 1 cards for the draw phase
Dare draws 3 cards for the draw phase
akodobill1 passes
Dare plays Hige's Sermon to bow Vice Proprietor and Master Tactician
akodobill1 plays Ready for Battle to ready Master Tactician
Dare plays Censure to cancel the effects of Ready for Battle
akodobill1 passes
Dare uses City of the Open Hand, bowing City of the Open Hand to take 0 honor from akodobill1

CotoH doesnt seem to work , this happened twice
Guessing a misinteraction with Silent Ones Monestary

**Comment by The-Outcast** [comment]
Well the bug would be that he was able to bow City when it wouldn't change the gamestate? Because they are still in the same phase here.

**Comment by marcsoiferman** [comment]
I think it's just a chat issue
