### ISSUE TITLE
Bug: Lost papers and Season of war

### ISSUE THREAD

**Issue by Chiller2060** [ringteki/ringteki#486]
Hi Guys,

When revealing Lost papers using season of war, the reaction cannot be triggered.
Neithertheless, it's occuring during the dynasty phase, a new one, but still one. 

That's specific and different from using, for example, "walking the way" during another phase.
Thx a lot

**Comment by marcsoiferman** [comment]
"Refill faceup" is not the same as revealing, so this is working as intended.
