### ISSUE TITLE
where is api/fomarts

### ISSUE THREAD

**Issue by wu123456** [ringteki/ringteki#913]
I build this website in China. But in the new version, add new api called "api/fomarts" , but it seems that the sever code do not contain it.
I need help.

**Comment by marcsoiferman** [comment]
It's in the client.  Some of the code is duplicated in both & needs to be cleaned up to be removed from one or the other.

https://github.com/ringteki/ringteki-client

https://github.com/ringteki/ringteki-client/blob/0c1bb9df1b4a8e75e10cc3e7c657283f30fcae19/server/api/cards.js#L42
